import pandas as pd
import json

df = pd.read_csv('backend/data/diabetic_data.csv')
print('=== GENDER ===')
print(df['gender'].value_counts().to_dict())
print('=== AGE ===')
print(df['age'].value_counts().to_dict())
print('=== RACE ===')
print(df['race'].value_counts().to_dict())
print('=== READMITTED ===')
print(df['readmitted'].value_counts().to_dict())
print('=== TIME_IN_HOSPITAL ===')
print(df['time_in_hospital'].describe().to_dict())
print('=== NUM_DIAGNOSES ===')
print(df['number_diagnoses'].describe().to_dict())
print('=== NUM_MEDICATIONS ===')
print(df['num_medications'].describe().to_dict())
print('=== INSULIN ===')
print(df['insulin'].value_counts().to_dict())
print('=== DIAG_1 top ===')
print(df['diag_1'].value_counts().head(10).to_dict())
print('=== ADMISSION_TYPE ===')
print(df['admission_type_id'].value_counts().to_dict())
print('=== TIME_IN_HOSPITAL DISTRIBUTION ===')
print(df['time_in_hospital'].value_counts().sort_index().to_dict())
print('=== NUMBER_INPATIENT ===')
print(df['number_inpatient'].value_counts().head(8).to_dict())
print('=== NUMBER_EMERGENCY ===')
print(df['number_emergency'].value_counts().head(8).to_dict())
print('=== CHANGE ===')
print(df['change'].value_counts().to_dict())
print('=== DIABETESMED ===')
print(df['diabetesMed'].value_counts().to_dict())
