apiVersion: v1
kind: Service
metadata:
  name: flower-server-service
  namespace: federamed-ai
  labels:
    app: flower-server
spec:
  type: ClusterIP
  selector:
    app: flower-server
  ports:
    - name: grpc
      port: 9092
      targetPort: 9092
      protocol: TCP
    - name: http-health
      port: 8080
      targetPort: 8080
      protocol: TCP